### ISSUE TITLE
show_progress  not defined in admm_problem

### ISSUE THREAD

**Issue by dave31415** [cvxgrp/ncvx#2]
When running
python examples/job_selection.py

Traceback (most recent call last):
  File "job_selection.py", line 34, in <module>
    val, resid = prob.solve(method="relax-round-polish", polish_depth=5)
  File "/Users/davej/anaconda2/anaconda/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 171, in solve
    return func(self, _args, *_kwargs)
  File "/Users/davej/anaconda2/anaconda/lib/python2.7/site-packages/ncvx-0.1.3-py2.7.egg/ncvx/admm_problem.py", line 306, in relax_round_polish
    0, polish_depth, show_progress)
NameError: global name 'show_progress' is not defined

**Comment by SteveDiamond** [comment]
This works for me. Maybe it's fixed on the 0.1.4 version now on PyPi?
