### ISSUE TITLE
examples/max_coverage.py - "TypeError: 'Prox' object is not callable"

### ISSUE THREAD

**Issue by mikeroberts3000** [cvxgrp/ncvx#5]
Hey Steven,

Running ``examples/max_coverage.py`` also returns an error for me:

```
DN0a22a81f:examples mike$ python max_coverage.py
Traceback (most recent call last):
  File "max_coverage.py", line 24, in <module>
    prob.solve(method="NC-ADMM", parallel=False, verbose=True, polish_depth=0, restarts=1)
  File "/Users/mike/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/cvxpy-0.4.9-py2.7.egg/cvxpy/problems/problem.py", line 207, in solve
    return func(self, *args, **kwargs)
  File "/Users/mike/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ncvx-0.1.4-py2.7.egg/ncvx/admm_problem.py", line 279, in admm
    prox_polished, polish_depth, lower_bound, alpha, args, kwargs) for idx, rho_val in enumerate(rho)])
  File "/Users/mike/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ncvx-0.1.4-py2.7.egg/ncvx/admm_problem.py", line 90, in admm_inner_iter
    x1 = prox(x0, rho_val)
TypeError: 'Prox' object is not callable
```

Am I on the wrong version of something? As far as I'm aware, I have the latest version of cvxpy and the latest version of ncvx. Note that I was able to successfully run ``examples/circle_packing.py``.

**Comment by reachablesa** [comment]
Hi,
I have the same problem.

**Comment by SteveDiamond** [comment]
Sorry for the super slow response. This is fixed now in source and on pip. It was because scsprox is out of date on pip. I've posted an issue asking the maintainer to update it.

**Comment by mikeroberts3000** [comment]
This example works for me now 😄
